<?php

/**
 * @file
 * Contains cke_bt_table.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cke_bt_table_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cke_bt_table module.
    case 'help.page.cke_bt_table':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bootstrap table tools') . '</p>';
      return $output;

    default:
  }
}
